import os
import smtplib
from pathlib import Path
from email.message import EmailMessage

from dotenv import load_dotenv


class EmailSender:

    def __init__(self):

        load_dotenv()

        self.sender = os.getenv("EMAIL_ADDRESS")
        self.password = os.getenv("EMAIL_PASSWORD")
        self.receiver = os.getenv("EMAIL_RECEIVER")

    def send_report(self, report_path, resources):

        message = EmailMessage()

        message["Subject"] = "🚨 Terraform Drift Detected"
        message["From"] = self.sender
        message["To"] = self.receiver

        body = f"""
Terraform Drift Detection Report

Resources Drifted : {len(resources)}

Please find the attached HTML report.

Generated by Terraform Drift Detector.
"""

        message.set_content(body)

        report_path = Path(report_path)

        with open(report_path, "rb") as file:

            message.add_attachment(
                file.read(),
                maintype="text",
                subtype="html",
                filename=report_path.name
            )

        with smtplib.SMTP("smtp.gmail.com", 587) as smtp:

            smtp.starttls()

            smtp.login(
                self.sender,
                self.password.replace(" ", "")
            )

            smtp.send_message(message)